apiVersion: hugo.gohugo.io/v1alpha1
kind: Hugo
metadata:
  labels:
    app.kubernetes.io/name: hugo
    app.kubernetes.io/instance: hugo-sample
    app.kubernetes.io/part-of: hugo-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: hugo-operator
  name: hugo-sample
spec:
  replicas_size: 1
  archive:
    url: "https://github.com/OlafRadicke/olaf-radicke-de/archive/refs/tags/4.0.tar.gz"
    format: "tar.gz"
    dir: "olaf-radicke-de-4.0"
    hugo_dir: ""
    hugo_base_url: "https://olaf-radicke.de"

