---

- name: start hugo
  kubernetes.core.k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: '{{ ansible_operator_meta.name }}-nginx'
        namespace: '{{ ansible_operator_meta.namespace }}'
      spec:
        replicas: "{{ replicas_size }}"
        selector:
          matchLabels:
            app: hugo
        template:
          metadata:
            labels:
              app: hugo
          spec:
            containers:
            - name: nginx
              image: "docker.io/nginxinc/nginx-unprivileged"
              ports:
                - containerPort: 8080