---

- name: start hugo
  kubernetes.core.k8s:
    definition:
      kind:                       Deployment
      apiVersion:                 apps/v1
      metadata:
        name:                     '{{ ansible_operator_meta.name }}'
        namespace:                '{{ ansible_operator_meta.namespace }}'
        labels:
          app:                    hugo
      spec:
        replicas:                 "{{ replicas_size }}"
        selector:
          matchLabels:
            app:                  hugo
        template:
          metadata:
            labels:
              app:                hugo
          spec:
            initContainers:
            - name:               '{{ ansible_operator_meta.name }}-init-container'
              image:              '{{ init_container_image }}'
              env:
                - name:           ARCHIVE_URL
                  value:          "{{ archive.url }}"
                - name:           ARCHIVE_FORMAT
                  value:          "{{ archive.format }}"
                - name:           ARCHIVE_DIR
                  value:          "{{ archive.dir }}"
                - name:           ARCHIVE_HUGO_DIR
                  value:          "{{ archive.hugo_dir }}"
                - name:           HUGO_BASE_URL
                  value:          "https://olaf-radicke.de"
                - name:           TARGET_DIR
                  value:          "{{ static_html_dir }}"
              volumeMounts:
                - name:           static-html
                  mountPath:      "{{ static_html_dir }}"
            containers:
            - name:               '{{ ansible_operator_meta.name }}-nginx'
              image:              "{{ service_container_image }}"
              ports:
                - name:           web-ui
                  containerPort:  8080
              volumeMounts:
              - name:             static-html
                mountPath:        "{{ static_html_dir }}"
            volumes:
            - name:               static-html
              emptyDir:           {}


- name: start hugo service
  kubernetes.core.k8s:
    definition:
      apiVersion:                 v1
      kind:                       Service
      metadata:
        name:                     '{{ ansible_operator_meta.name }}'
        namespace:                '{{ ansible_operator_meta.namespace }}'
      spec:
        selector:
            app:                  hugo
        ports:
          - protocol:             TCP
            port:                 80
            targetPort:           web-ui
            type:                 ClusterIP